### ISSUE TITLE
Facebook can't login

### ISSUE THREAD

**Issue by mvaragnat** [Weetbix/facebot#1]
Hello, this looks like an awesome hack,

However when I try to connect with my credentials I get

```
Error in login: Couldn't login. Facebook might have blocked this account. Please login with a browser or enable the option 'forceLogin' and try again. 
```

Is it possible that Facebook has blocked access to this hack?

**Comment by mvaragnat** [comment]
You can close this - it was Facebook thinking a login from Ashburn, VA (Heroku location) was suspicious.

**Comment by Weetbix** [comment]
Thanks @mvaragnat :smile: 

Yeah, unfortunately when logging in from another country (such as a heroku instance) you will occasionally get blocked by Facebooks suspicious login attempt system.

Even more unfortunately I have found that after a few days facebook may block you and force you to change password. I think the only way around this would be to turn off login notifications (although I haven't tested that yet).

The most bulletproof way around this is to run the app locally, which is pretty easy but obviously inconvenient unless you have a box running all the time already.

**Comment by mvaragnat** [comment]
Yeah pretty inconvenient lol :-)

I don't think I'll be running it permanently anyway, it was more to see how it worked. Very clever. I'm waiting impatiently for the official API release, perhaps you'd want to chat about it? You can reach me by Slack if you want using my [Smooz connection](http://www.smooz.io/guest/567d2108b9988b1100b1e9d8).
